version: '3.8'
services:
  exam-system:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: exam-system
    ports:
      - "8081:8080"
    networks:
     - smileshark
  exam-system-client:
    image: nginx
    container_name: exam-system-client
    restart: always
    ports:
      - "8887:80"
    volumes:
      - ./client/exam-system-client/dist:/usr/share/nginx/html
      - ./docker-project/exam-system-client/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - smileshark
networks:
  smileshark:
     external: true